### ISSUE TITLE
User database new attribute required

### ISSUE THREAD

**Issue by Blaiteray** [syedfaysel/BeIntelligent#12]
There is a feature about showing user's **recommended book**. So a genre selection page was made in the frontend. While signing up, an user have to select some genre to finish their sign up, so that based on the genres a list of book can be shown. So, a new attribute about user's preferred genre is needed in the database. The changes are:
- [x] New attribute in database contating a list of genre the user will input while signing up.
- [x] Register `POST` request and Login `POST` response will also carry this new attribute.

**Comment by syedfaysel** [comment]
updated user collection, now contains a list, preferredGenres.
signup, login response along with entire `user`
